version: '2.1'

networks:
    extnetwork:
      name: chubaodb-extnetwork  
      ipam:
         config:
         - subnet: 192.168.0.0/24
           gateway: 192.168.0.1

services:
    build:
        image: rust:latest
        volumes:
            - ../:/rust/chubaodb
            - ~/.cargo/registry/:/usr/local/cargo/registry/
        command:
            - bash
            - "-c"
            - >-
              set -e;
              echo "Install clang...";
              apt-get update &> /dev/null && apt-get install clang -y &> /dev/null;
              echo "Install rustup component 'rustfmt'...";
              rustup component add rustfmt --toolchain 1.41.0-x86_64-unknown-linux-gnu &> /dev/null;
              cd /rust/chubaodb;
              echo "Build project...";
              cargo build --release;
              cp /rust/chubaodb/target/release/chubaodb /rust/chubaodb/docker/build/
        networks:
            extnetwork:

